export const TRANSACTION_TYPES = {
  //   CANCEL: 'cancel',
  CONTRACT_INTERACTION: "contractInteraction",
  DEPLOY_CONTRACT: "contractDeployment",
  DEPLOY_WALLET: "deployWallet",
  //   ETH_DECRYPT: MESSAGE_TYPE.ETH_DECRYPT,
  //   ETH_GET_ENCRYPTION_PUBLIC_KEY: MESSAGE_TYPE.ETH_GET_ENCRYPTION_PUBLIC_KEY,
  //   INCOMING: 'incoming',
  //   PERSONAL_SIGN: MESSAGE_TYPE.PERSONAL_SIGN,
  //   RETRY: 'retry',
  //   SIGN: MESSAGE_TYPE.ETH_SIGN,
  //   SIGN_TYPED_DATA: MESSAGE_TYPE.ETH_SIGN_TYPED_DATA,
  SEND: "send",
  //   SMART: 'smart',
  //   SWAP: 'swap',
  //   SWAP_APPROVAL: 'swapApproval',
  TOKEN_APPROVE: "approve",
  TOKEN_SET_APPROVAL_FOR_ALL: "setapprovalforall",
  TOKEN_SAFE_TRANSFER_FROM: "safetransferfrom",
  TOKEN_TRANSFER: "transfer",
  TOKEN_TRANSFER_FROM: "transferfrom",
};
